# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Ngx-components packages deployment on github packages

on:
  push:
    branches:
      - ng-v13

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@iazlabs"
      - name: Check npm version
        run: npm -v

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Build ngx-dropzone
        run: npm run build @azlabs/ngx-dropzone

      - name: Build ngx-intl-tel-input
        run: npm run build @azlabs/ngx-intl-tel-input

      - name: Build ngx-smart-form
        run: npm run build @azlabs/ngx-smart-form

      - name: Publish ngx-dropzone
        run: cd dist/azlabs/ngx-dropzone && npm publish

      - name: Publish ngx-intl-tel-input
        run: cd dist/azlabs/ngx-intl-tel-input && npm publish

      - name: Publish ngx-smart-form
        run: cd dist/azlabs/ngx-smart-form && npm publish
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
